#  _ =  require "underscore"
#  $ =  require "jquery"
#  Marionette = require "marionette"
#  React = require "react"
#  TweenLite = require "TweenLite"
#  TimelineLite = require "TimelineLite"
#  TweenMax = require "TweenMax"
#  TimelineMax = require "TimelineMax"
#  TimelineMax = require "TimelineMax"
#  Modernizr = require "modernizr"
#  Platform = require "platform"
#  Device = require "device"
#  Hammer = require "hammer"
#  require "owl.carousel"
#  require "bootstrap"
